
name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: bengdocker
        password: dckr_pat_4hx38SiTfqweucG-onJ2bpMTlBA

        
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push WebGoat Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}
        docker push ${{ secrets.DOCKER_USERNAME }}
#added comments for filler newest again 14:49
#newest comment 16:27 with Nir
